<?php

namespace AppBundle\Repository;

/**
 * EventPurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventPurchaseRepository extends \Doctrine\ORM\EntityRepository
{
}
