<?php

namespace AppBundle\Repository;

/**
 * InvitationRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
