<?php

namespace AppBundle\Repository;

/**
 * MemberShipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberShipRepository extends \Doctrine\ORM\EntityRepository
{
}
