<?php

/*
 * This file is part of the Instan't App project.
 *
 * (c) Instan't App <contact@instant-app.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Developed by MIT <contact@mit-agency.com>
 *
 */

namespace AppBundle\Repository;

use AppBundle\Entity\Plan;

/**
 * PlanRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRepository extends BaseRepository
{
    /**
     * @param $key
     *
     * @throws \InvalidArgumentException
     *
     * @return null|Plan
     */
    private function findOneByKey($key)
    {
        if (in_array($key, Plan::supportedPlanKeys(), true)) {
            return $this->findOneBy(['planKey' => $key]);
        }

        throw new \InvalidArgumentException(sprintf('Unsupported key %s', $key));
    }

    /**
     * @return null|Plan
     */
    public function getFreePlan()
    {
        return $this->findOneByKey(Plan::FREE_PLAN_KEY);
    }

    /**
     * @return null|Plan
     */
    public function getPremiumPlan()
    {
        return $this->findOneByKey(Plan::PREMIUM_PLAN_KEY);
    }

    /**
     * @return null|Plan
     */
    public function getStarterPlan()
    {
        return $this->findOneByKey(Plan::STARTER_PLAN_KEY);
    }

    /**
     * @return null|Plan
     */
    public function getLuxuryPlan()
    {
        return $this->findOneByKey(Plan::LUXURY_PLAN_KEY);
    }
}
