<?php

/*
 * This file is part of the Instan't App project.
 *
 * (c) Instan't App <contact@instant-app.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * Developed by MIT <contact@mit-agency.com>
 *
 */

namespace AppBundle\Repository;

/**
 * UserRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseRepository
{
    /**
     * @param string $role
     * @return mixed
     */
    public function getNbUsersByRole($role = "ROLE_SUPER_ADMIN")
    {

        if( $role === "ROLE_USER" ){
            $query=' u.roles = :roles';
            $role = 'a:0:{}';
        }else{
            $query='u.roles LIKE :roles';
            $role = '%"'.$role.'"%';
        }

        $qb = $this->createQueryBuilder('u');

        $res =
            $qb
                ->select("COUNT(u) as NB_USERS")
                ->where($query)
                ->setParameter('roles', $role)
                ->getQuery()
                ->getResult()
        ;
        return $res;
    }

    /**
     * @return mixed
     */
    public function getNbUsersDisabled()
    {
        $qb = $this->createQueryBuilder('u');

        $res =
            $qb
                ->select("COUNT(u) as NB_USERS")
                ->where('u.enabled = 0')
                ->getQuery()
                ->getResult()
        ;
        return $res;
    }
}
