imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: api_filters.yml }
    - { resource: 'vendor/knp_gaufrette.yml' }
    - { resource: 'vendor/payum.yml' }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: { enabled: true }
    csrf_protection: { enabled: true }
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: { enabled: false }
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'Form/fields.html.twig'
    globals:
        google_analytics: "%google_analytics%"
        play_store_download_link: '#'
        app_store_download_link: '#'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        server_version: '5.7'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# Nelmio CORS
nelmio_cors:
    defaults:
        allow_origin: ['%cors_allow_origin%']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
        allow_headers: ['*']
        max_age: 3600
    paths:
        '^/': ~

api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/AppBundle/DTO']
    enable_fos_user: true
    http_cache:
        invalidation:
            enabled: true
            #varnish_urls: '%varnish_urls%'
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
        public: true

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_name%"
    registration:
        form:
            type: AppBundle\Form\Type\RegistrationType
            validation_groups: [App]
        confirmation:
            enabled:              true
            template:             '@FOSUser/Registration/email.html.twig'
            from_email:
                address: "%mailer_user%"
                sender_name: "%mailer_name%"
    profile:
        form:
            type: AppBundle\Form\Type\ProfileType
    change_password:
        form:
            type: AppBundle\Form\Type\ChangePasswordType


lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'

hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]
    connect:
        account_connector: app.security.user_provider
    fosub:
        username_iterations: 30
        properties:
            facebook:   facebookId
            google:     googleId
    resource_owners:
        facebook:
            type:                facebook
            client_id:           '%facebook_id%'
            client_secret:       '%facebook_secret%'
            scope:               "public_profile,email,user_friends"
            options:
                display: popup #dialog is optimized for popup window
                auth_type: rerequest # Re-asking for Declined Permissions
                csrf: true
            infos_url: 'https://graph.facebook.com/v2.7/me?fields=first_name,last_name,name,email,gender,picture'
        google:
            type:                google
            client_id:           '%google_id%'
            client_secret:       '%google_secret%'
            scope:               "email profile"
            options:
                csrf: true

knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: KnpMenuBundle::menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig

stof_doctrine_extensions:
    default_locale: '%locale%'
    uploadable:
        # Default file path: This is one of the three ways you can configure the path for the Uploadable extension
        default_file_path:       "%kernel.root_dir%/../web/uploads"

        # Mime type guesser class: Optional. By default, we provide an adapter for the one present in the HttpFoundation component of Symfony
        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter

        # Default file info class implementing FileInfoInterface: Optional. By default we provide a class which is prepared to receive an UploadedFile instance.
        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
    orm:
        default:
            timestampable: true
            uploadable: true

ivory_ck_editor:
    configs:
        my_config:
            toolbar: [ ['Bold', 'Italic'],["Format"]["Font"] ["FontSize"] ,["NumberedList"]  ["BulletedList"] ,["JustifyLeft"]["JustifyCenter"]["JustifyRight"] ["JustifyBlock"], ["TextColor"]["BGColor"] ]
            uiColor: "#ffffff"

liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        media_thumb:
            quality: 80
            filters:
                thumbnail: { size: [130, 130], mode: outbound }
        training_widget:
            quality: 80
            filters:
                thumbnail: { size: [300, 300], mode: outbound }
