app_event:
    resource: "@AppBundle/Controller/Admin/EventController.php"
    type:     annotation

app_user:
    resource: "@AppBundle/Controller/Admin/UserController.php"
    type:     annotation

api:
    resource: '.'
    type: 'api_platform'
    prefix: /api

app:
    resource: '@AppBundle/Action/'
    type: 'annotation'
    prefix: /api

app_routing:
    resource: '@AppBundle/Controller/'
    type: 'annotation'
    prefix: /

home:
    path: /

app_logout:
    path: /logout
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /auth/logout
        permanent: true

api_login_check:
    path: /api/login_check

payum_all:
    resource: "@PayumBundle/Resources/config/routing/all.xml"

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
  prefix: /auth

facebook_login:
    path: /auth/login/check-facebook

google_login:
    path: /auth/login/check-google

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /auth/connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /auth/connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /auth/login

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    
